name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
      - "develop"
      # Add other branches as needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish-storybook
      uses: bitovi/github-actions-storybook-to-github-pages@dependabot/github_actions/github-actions-majors-e6ee9d7de3
      with:
        path: dist/storybook/${{ github.ref_name }}
        build_command: npm run build-storybook-${{ github.ref_name }}
        #checkout: false